const tasks = [
    {
        id: 11,
        title: 'Create Task',
        date: '2022-09-12',
        duration: '15 minute',
        project: 'Bob AI',
        color: '#38A98E',
    },
    {
        id: 12,
        title: 'Research Dashboard',
        date: '2022-03-10',
        duration: ' 15 minute',
        project: 'New City',
        color: '#FF8A9F',
    },
    {
        id: 13,
        title: 'Feedbacks',
        date: '2022-01-30',
        duration: ' 15 minute',
        project: 'Bob AI',
        color: '#38A98E',
    },
    {
        id: 14,
        title: 'Sign up',
        date: '2022-05-14',
        duration: ' 15 minute',
        project: 'Mapplo',
        color: '#39B9CE',
    },
    {
        id: 15,
        title: 'Research Dashboard',
        date: '2022-06-07',
        duration: ' 15 minute',
        project: 'New City',
        color: '#FF8A9F',
    },
    {
        id: 16,
        title: 'Sign up',
        date: '2022-05-12',
        duration: ' 15 minute',
        project: 'Mapplo',
        color: '#39B9CE',
    },
    {
        id: 17,
        title: 'Create Task',
        date: '2022-09-22',
        duration: ' 15 minute',
        project: 'Bob AI',
        color: '#38A98E',
    },
    {
        id: 18,
        title: 'Feedbacks',
        date: '2022-05-08',
        duration: ' 15 minute',
        project: 'Bob AI',
        color: '#38A98E',
    },
    {
        id: 19,
        title: 'Sign up',
        date: '2022-07-12',
        duration: ' 15 minute',
        project: 'Mapplo',
        color: '#39B9CE',
    },
    {
        id: 20,
        title: 'Create Task',
        date: '2022-10-12',
        duration: ' 15 minute',
        project: 'Bob AI',
        color: '#38A98E',
    },
    {
        id: 21,
        title: 'Sign up',
        date: '2022-08-10',
        duration: ' 15 minute',
        project: 'Mapplo',
        color: '#39B9CE',
    },
    {
        id: 22,
        title: 'Research Dashboard',
        date: '2022-02-02',
        duration: ' 15 minute',
        project: 'New City',
        color: '#FF8A9F',
    },
    {
        id: 23,
        title: 'Sign up',
        date: '2022-06-24',
        duration: ' 15 minute',
        project: 'Mapplo',
        color: '#39B9CE',
    },
    {
        id: 24,
        title: 'Feedbacks',
        date: '2022-11-11',
        duration: ' 15 minute',
        project: 'Bob AI',
        color: '#38A98E',
    },
];

export default tasks
